SELECT
  PROJECT.Pnumber ,
  PROJECT.Dnum ,
  PROJECT.Lname ,
  EMPLOYEEMPLOYEE.Address,
  EMPLOYEEMPLOYEE.Bdate 
FROM
  PROJECT 
  JOIN DEPARTMENT ON P.Dnum = DEPARTMENT.Dnumber
  JOIN EMPLOYEE ON DEPARTMENT.Mgr_ssn = EMPLOYEEMPLOYEE.Ssn
WHERE
  PROJECT.Plocation = 'Stafford';

